version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_bot
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./bot:/app
    command: ["python", "main.py"]

  redis:
    image: redis:7
    container_name: services
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
volumes:
  redis-data:
